""" THIS PROGRAM WILL NOT HAVE ANY PROGRAM IT WILL CONTAIN SOME TYPES OF THEORY NOTES  AND SOME IMP..
        SO THIS USED IS MULTILINE COMMENT.IT IS GIVEN USING THREE DOUBLE INVERTED COMMAS(") """
# THIS SYMBOL (#) IS USED FOR SINGLE LINE COMMENT.
#TASK:- GOOGLE OUT ALL ESCAPE SEQUENCE CHARACTER AND INBUILT MODULE OF PYTHON...(FROM VIDEO 1 TO 7)
"""import flask
print("HELLO WORLD!!", "I AM ATHARVA MANJREKAR") # THIS IS BASIC PRINTING METHOD
print("c:\\nello world\n INDIA IS MY COUNTRY\tPROUD TO BE INDIAN.")"""
# STARTING PYTHON VERY SERIOUSLY FROM HERE i.e VIDEO 8

# VIDEO NO:- 8
""" 1) PYTHON HAS INBUILT CALCULATOR WHICH DOES BASIC OPERATIONS LIKE ADDITION,SUBTRACTION,MULTIPLICATION AND
 DIVISION...
    2) SO IN PYTHON WE CAN DIRECTLY ADD TWO INTEGER AND FLOAT OR ONE FLOAT AND ONE INTEGER ALSO WE CAN ADD TWO
     STRINGS WITH EACH ANOTHER.."""
var1=20
var2=40.30
abc="Atharva "
pqr="Manjrekar"
print(type(var1))
print(type(var2))
print(type(abc))
print(type(pqr))
print(var1+var2)
print(abc+pqr)
print(var2+var1)


